<link rel="stylesheet" type="text/css" href="css/gioithieu.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<div class="">
    <div style="width:100% ;background:#000;color:#fff; padding:5px ; margin-bottom:10px"><h5 >Introduce</h5></div>
	
    <div class="about" style="margin-left:20px;">
    	<p>© 2018. Mobile World Joint Stock Company. Business Registration Certificate: 0303217354 issued by the Department of Planning and Investment of Ho Chi Minh City on January 2, 2007. Social Business Registration Certificate: 238/GP-BTTTT issued by the Ministry of Information and Communications on June 4, 2020.
        Address: 128 Tran Quang Khai, Tan Dinh Ward, District 1, Ho Chi Minh City. Phone: 028 38125960. Email: cskh@thegioididong.com. Responsible for content: Huynh Van Tot. See terms of use</p>
        <p><span>Head office</span><br />• No. 25, Lane 178/71 Tay Son, Trung Liet, Dong Da, Hanoi</p>	
			<p><span>Other Facilities</span><br />• CS 1: 5th Floor - Building A4, Lane 120 Hoang Quoc Viet, Cau Giay, Hanoi<br />• CS 2: No. 23, Lane 178/71 Tay Son, Trung Liet, Dong Da, Hanoi<br />
        <!-- <p><span>Mục tiêu đào tạo của chúng tôi đó là</span><br />• Cung cấp những kiến thức "chuẩn", "mới nhất" đến các học viên cũng như cho cộng đồng.<br />• Đem đến cho học sinh, sinh viên cách tư duy, nghiên cứu một cách hiện đại và khoa họcĐào tạo nguồn nhân lực chất lượng cao phục vụ cho ngành CNTT nước nhà</p>
        <p><span>Môi trường đào tạo tại trung tâm</span><br />• Với cả hai hình thức đào tạo Trực tiếp & Trực tuyến, Trung Tâm VIETPRO đã mang đến cho mỗi học viên cơ hội giao lưu cùng toàn thể các bạn đam mê CNTT trên cả nước, tạo môi trường hòa đồng và thân thiện giữa các học viên của cả 3 miền bắc, trung, nam.<br />• Trung tâm luôn luôn có những giảng viên hỗ trợ Trực tiếp & Trực tuyến cho các học viên 12/24 ngoài giờ học để giải đáp những thắc mắc, vấn đề chưa hiểu trong bài học cũng như hướng dẫn các học viên cách thức để hoàn thiện đồ án cuối khóa của mình một cách tôt nhất.<br />• Ngoài ra trung tâm VIETPRO còn tổ chức nhiều hoạt động ngoại khóa bổ ích để các học viên có cơ hội giao lưu và học hỏi lẫn nhau về những vấn đề trong học tập, nghiên cứu cũng như các vấn đề xã hội lành mạnh khác</p>
        <p><span>Đội ngũ giảng viên của trung tâm chúng tôi</span><br />• Với đội ngũ giảng viên trẻ và vô cùng năng động, nhiệt huyết, tận tụy và đam mê với chuyên ngành của mình sẽ là những người thầy, người cô gần gũi với các học viên trong suốt quá trình học tập và nghiên cứu của mình.<br />• Trung tâm chúng tôi có thể tự hào về chất lượng của đội ngũ giảng viên đang công tác cho trung tâm. Họ là những người trẻ, có tài, đều là những kỹ sư, thạc sỹ năng động của thế hệ 8X từng làm việc tại nhiều vị trí như: Team Leader Outsourcing, Giảng viên của một số trường Cao đẳng & Đại học Kỹ thuật danh tiếng trên cả nước.</p>
        <p><span>Vấn đề học phí và các ưu đãi khác</span><br />• Đây chính là một trong những vấn đề mà các học viên quan tâm nhất, biết được điều đó, trung tâm đào tạo lập trình và đồ họa website VIETPRO chúng tôi đã đưa mục này vào mục chú ý thứ hai sau mục chất lượng đào tạo của mình.<br />• Ngoài việc tự hào về chất lượng đào tạo của mình, Trung Tâm VIETPRO còn tự tin khẳng định về học phí của các khóa học tại trung tâm là rất thấp so với lượng kiến thức mà chúng tôi cung cấp cho các học viên. Bởi vì chúng tôi muốn tất cả mọi người đều có thể theo học được các khóa đào tạo của trung tâm mà không phải quan tâm đến vấn đề học phí, nhất là tầng lớp Sinh viên và Học sinh.<br />• Ngoài ra, trung tâm còn có nhiều hình thức ưu đãi khác rất bổ ích khi đăng ký tham gia các khóa học như: Chế độ giảm học phí, chế độ học bổng, chế độ tặng thưởng, các Party Offline cũng như các phong trào hoạt động thể dục thể thao ngoại khóa khác…</p>
        <p id="signature"><span>vietpro education</span></p> -->
    </div>
</div>
